### ISSUE TITLE
Full support for newest Live For Speed version

### ISSUE THREAD

**Issue by JustSig** [Dygear/PRISM#67]
Full support for newest Live For Speed version 0.6U. Update Insim version to 8.
// New value PMO_POSITION for IS_AXM packet to report a blank position
// New packet IS_CIM reports a connection's interface mode
// New values TTC_SEL_START and TTC_SEL_STOP for IS_TTC
// New value PMO_GET_Z for IS_AXM packet to report Z values
// New values PMO_SELECTION_REAL, PMO_MOVE_MODIFY, PMO_AVOID_CHECK

**Comment by Dygear** [comment]
So I've been waiting to reply to this for some time now because I knew that PHP 7.4 alpha was about to drop. The next version of PRISM will very likely be version 0.9.0 and once it reaches stable it will be 1.0.0. The reason for this is because, PHP 7.4.0 alpha 1 introduced a new interface called the [FFI or Foreign Function Interface](https://wiki.php.net/rfc/ffi) to PHP. What that does is, allow for PHP to directly interact with C code. So now when ever there is an update to InSim, all you need to do is pop the InSim.h file into the PRISM directory and it will have access to all of the InSim related structs.

The method for loading the InSim.h file into PHP is outline here ... [`FFI::load(string $file_name): FFI`](https://wiki.php.net/rfc/ffi#ffiload_string_file_nameffi).

**Comment by ScottLync** [comment]
> Full support for newest Live For Speed version 0.6U. Update Insim version to 8.
> // New value PMO_POSITION for IS_AXM packet to report a blank position
> // New packet IS_CIM reports a connection's interface mode
> // New values TTC_SEL_START and TTC_SEL_STOP for IS_TTC
> // New value PMO_GET_Z for IS_AXM packet to report Z values
> // New values PMO_SELECTION_REAL, PMO_MOVE_MODIFY, PMO_AVOID_CHECK

Version has been increased.



> So I've been waiting to reply to this for some time now because I knew that PHP 7.4 alpha was about to drop. The next version of PRISM will very likely be version 0.9.0 and once it reaches stable it will be 1.0.0. The reason for this is because, PHP 7.4.0 alpha 1 introduced a new interface called the [FFI or Foreign Function Interface](https://wiki.php.net/rfc/ffi) to PHP. What that does is, allow for PHP to directly interact with C code. So now when ever there is an update to InSim, all you need to do is pop the InSim.h file into the PRISM directory and it will have access to all of the InSim related structs.
> 
> The method for loading the InSim.h file into PHP is outline here ... [`FFI::load(string $file_name): FFI`](https://wiki.php.net/rfc/ffi#ffiload_string_file_nameffi).

I think now you can close this issue. Right?
